Effect: Allow
Action:
  - dynamodb:Query
  - dynamodb:Scan
  - dynamodb:GetItem
  - dynamodb:PutItem
  - dynamodb:UpdateItem
  - dynamodb:DeleteItem
  - dynamodb:DescribeTable
  - dynamodb:BatchWriteItem
Resource: 
  - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/users"
